# This code create the three dimensional array to describe the GPT4 standalone classifications from the multiple txt files generated by each agent.

# Store the possible agents
agent = c("1","2","3")

# Create the array squeleton
matrix_llmsa = array(data=0, dim=c(
  length(index),
  length(category),
  length(tone),
  length(agent)
), 
dimnames = list(index,category,tone,agent))


llm_uncleaned_folders = paste("data/GPT4/gpt4-lot",agent,"/llm_output_1/prompt_1/",sep="")

for(current_agent in 1:length(agent)){
  for(i in index){
    suppressWarnings({
      input = paste(trimws(readLines(paste(llm_uncleaned_folders[current_agent],i,"_output.txt", sep=""))))
    })
    current_category = ""
    
    # Read the input row by row
    for (row in 1:length(input)){
      
      #Check if a category is mentionned
      for(category_check in category){
        if(grepl(category_check, input[row])) current_category = category_check
      }
      
      # If there is a positive tone mentionned :
      if(grepl("positive", input[row]))if(substr(input[row],nchar('"positive": "')+1,nchar(input[row])-2)!="")
      {
        matrix_llmsa[i,current_category,"positive",current_agent] = 1
      }
      # If there is a negative tone mentionned :
      if(grepl("negative", input[row]))if(substr(input[row],nchar('"negative": "')+1,nchar(input[row])-2)!="")
      {
        matrix_llmsa[i,current_category,"negative",current_agent] = 1
      }
    }
  }
}

saveRDS(matrix_llmsa, "data/GPT4/matrix_GPT4_standalone.rds")
